- menu_name: "Services"

- name: "Kontakt"
  url: "/kontakt/"
  title: "Kontakt"

- name: "RSS"
  url: "/feed.xml"
  title: "RSS Feed abonnieren"

- name: "Atom"
  url: "/atom.xml"
  title: "Atom Feed abonnieren"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap für Google Webmaster Tools"