name: Update RWK

on:
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  updaterwk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install requests
          pip install PyYAML
      - name: Fetch RWK data
        run: |
          python _data/rwk.py
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add _data/rwk_data.yml _data/rwk_data.json
          git diff-index --quiet HEAD -- || git commit -m "Update RWK"; git push;
